import {test} from 'node:test';import assert from 'node:assert/strict';
import {MissionRuntime} from '../src/gameplay/MissionRuntime.js';
import {missionDefinitions} from '../src/gameplay/mission-definitions.js';
const pois=new Map(['regencia','temple','watertank','sector12','sector18','dblock'].map(id=>[id,{id,name:id,position:{x:0,z:0}}]));
const emit=(id,eventId,mode='walk')=>({type:'enteredPOI',poiId:id,eventId,mode});
test('all jobs validate against six stable map POIs',()=>{let m=new MissionRuntime({definitions:missionDefinitions,pois});assert.equal(m.invalid.size,0);assert.equal(m.definitions.size,4)});
test('six stop tour records unordered unique visits then finishes without duplicate scores',()=>{let m=new MissionRuntime({definitions:missionDefinitions,pois});assert.equal(m.start('explore-six-stops').ok,true);for(let i=0;i<6;i++){let id=['temple','sector18','dblock','regencia','watertank','sector12'][i],r=m.update(.05,{},[emit(id,i+1)]);assert.equal(r.at(-1).type,i===5?'missionFinished':'visitRecorded')}assert.equal(m.active,null);assert.deepEqual(m.snapshot().completed,['explore-six-stops']);assert.deepEqual(m.update(.05,{},[emit('regencia',7)]),[])});
test('courier enforces order and foot pickup, times out and does not accept same event twice',()=>{let m=new MissionRuntime({definitions:missionDefinitions,pois});m.start('courier-loop');assert.deepEqual(m.update(.1,{},[emit('temple',1)]),[]);assert.deepEqual(m.update(.1,{},[emit('regencia',2,'drive')]),[]);let r=m.update(.1,{},[emit('regencia',3,'walk')]);assert.equal(r[0].stage,1);assert.deepEqual(m.update(.1,{},[emit('regencia',3)]),[]);r=m.update(.1,{},[emit('temple',4,'drive')]);assert.equal(r[0].stage,2);r=m.update(.1,{},[emit('regencia',5)]);assert.equal(r.at(-1).type,'missionFinished');m.start('courier-loop');for(let i=0;i<5000;i++)m.update(.05,{},[]);assert.equal(m.active,null)});
test('missing POI never creates a fabricated job target',()=>{let m=new MissionRuntime({definitions:[{id:'bad',stages:[{type:'reachPOI',poiId:'missing'}]}],pois});assert.equal(m.start('bad').ok,false);assert.match(m.invalid.get('bad'),/POI/)});
